import './globals.css'
import type { Metadata } from 'next'
import localFont from "next/font/local"
import VtbLogo from "../public/vtb.png";
import Image from 'next/image';

const YANDEX_API = "364eecdb-ebf3-403c-a61f-1c05551a8765";

export const metadata: Metadata = {
    title: 'More Tech',
    description: 'Generated by МИСИС Харбинская лапша',
}

const VTB_Font = localFont({
    src: [
        {
            path: "./../public/VTBGroupUI-SemiBold.woff2",
            style: "normal",
            weight: "600",
        },
        {
            path: "./../public/VTBGroupUI-Medium.woff2",
            style: "normal",
            weight: "500",
        },
        {
            path: "./../public/VTBGroupUI-Regular.woff2",
            style: "normal",
            weight: "400",
        },
    ],
})

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <meta lang='ru'></meta>
            </head>
            <body className={[VTB_Font.className, "w-screen h-screen flex flex-col"].join(" ")}>
                <header>
                    <Image src={VtbLogo} alt="ВТБ" height={64} className='ml-[10%]'></Image>
                </header>
                    {children}
                </body>
        </html>
    )
}
