import { YMaps } from '@pbe/react-yandex-maps';
import './globals.css'
import type { Metadata } from 'next'
import { Inter, Golos_Text } from 'next/font/google'
import Script from 'next/script'

export const YANDEX_API = "364eecdb-ebf3-403c-a61f-1c05551a8765";
const inter = Golos_Text({ subsets: ['latin', 'cyrillic'], style: "normal" })

export const metadata: Metadata = {
    title: 'More Tech',
    description: 'Generated by МИСИС Харбинская лапша',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <head>
                <meta lang='ru'></meta>
            </head>
            <body className={[inter.className, "w-screen h-screen flex flex-col"].join(" ")}>
                    {children}
                </body>
        </html>
    )
}
