import './globals.css'
import type { Metadata } from 'next'
import VtbLogo from "../public/vtb.png";
import Image from 'next/image';
import { VTB_Font } from './vtb_font';

const YANDEX_API = "364eecdb-ebf3-403c-a61f-1c05551a8765";

export const metadata: Metadata = {
    title: 'More Tech',
    description: 'Generated by МИСИС Харбинская лапша',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="ru">
            <head>
                <link rel="icon" type="image/png" sizes="32x32" href="https://online.vtb.ru/favicon-32x32.png" />
                <link rel="icon" type="image/png" sizes="16x16" href="https://online.vtb.ru/favicon-16x16.png" />
                <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#1592f7" />
            </head>
            <body className={[VTB_Font.className, "w-screen h-screen flex flex-col"].join(" ")}>
                <header>
                    <Image src={VtbLogo} alt="ВТБ" height={64} className='ml-[10%]'></Image>
                </header>
                {children}
            </body>
        </html>
    )
}
